region = "us-east-1"
domain_name = "abctest.com"
vpc_cidr = "10.0.0.0/16"
azs = ["us-east-1a", "us-east-1b"]
access_log_bucket_name = "albtestaccesslogs121212"
kms_deletion_window_in_days = 7
app_healthcheck_path = "/index.html"
health_check_ineterval = 30
health_check_timeout = 5
key_name = "test-key"
ami_id = "ami-02dfbd4ff395f2a1b"
instance_type = "t3.medium"
ebs_volume_size = 8
alert_email = "anujbhagwat056@gmail.com"
